spring.application.name=dss-service
server.port=8082
spring.session.store-type=none

spring.cloud.stream.bindings.receiveTicket-in-0.destination=ticket-exchange
spring.cloud.stream.bindings.receiveTicket-in-0.group=support-queue
spring.cloud.stream.rabbit.bindings.receiveTicket-in-0.consumer.queue-name-group-only=true
# Numero di tentativi (default 3)
spring.cloud.stream.bindings.receiveTicket-in-0.consumer.max-attempts=5
# Quanto tempo aspettare tra un tentativo e l'altro (in millisecondi)
spring.cloud.stream.bindings.receiveTicket-in-0.consumer.back-off-initial-interval=2000
# Attiva automaticamente la creazione della DLQ
spring.cloud.stream.rabbit.bindings.receiveTicket-in-0.consumer.auto-bind-dlq=true
# Personalizza il nome della DLQ
spring.cloud.stream.rabbit.bindings.receiveTicket-in-0.consumer.dead-letter-queue-name=dss-service.support-tickets.errors
# (Opzionale) Aggiunge un prefisso comune a tutte le DLQ del binder
spring.cloud.stream.rabbit.binder.dlq-name-prefix=FAILED.

#pulizia url swagger
springdoc.api-docs.groups.enabled=true
server.forward-headers-strategy=framework

## =====================================================================
## INTEGRAZIONE CON CONFIG SERVER VIA EUREKA
## =====================================================================
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.config.import=optional:configserver:
spring.cloud.config.username=${CONFIG_SERVER_USER}
spring.cloud.config.password=${CONFIG_SERVER_PWD}